# tasks file for wordpress
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  become: yes

- name: Setting MySQL username
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)username_here(.*)$"
    replace: '\1{{ wp_mysql_user }}\2'

- name: Setting MySQL database
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)database_name_here(.*)$"
    replace: '\1{{ wp_mysql_db }}\2'

- name: Setting MySQL password
  become: yes
  replace:
    path: "/var/www/wordpress/wp-config.php"
    regexp: "(.*)password_here(.*)$"
    replace: '\g<1>{{ wp_mysql_password }}\g<2>'
